### ISSUE TITLE
Accessibility Summary final questions

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#135]
We agreed that a single issue would be created that identifies what yet remains to be done. That list is below.

* Should the table in the section Accessibility Conformance Related Statements use Example  statement 
instead of Suggested Summary?

* In the features table:
In long description is missing, protraying. is misspelled and should be portraying.

* Reading order is not filled in.  If the proper reading order is not present, it should be noted. I think this should be filled in.

* In structural navigation there is a dangling word "navigation"

* Transcript has no information field. It should say that if transcripts of audio are provided, it should be noted.

* TTS markup has no example. We should get something from the Pronunciation task force. George sent an email requesting this.  Also, there is a typo in the information,  it should be provided, missing the d.

* We have two examples. Do we want to add more? If yes, who wants to write it?

* Is the acknowledgements complete?
* The editors are in the acknowledgements, is that customary?

**Comment by dazrand** [comment]
I agree the Accessibility Conformance Related Statements table should use Example Statement, it offers more clarity. 

displayTransformability should the two table examples be listed consecutively?

The readingOrder would only play into the Example Statement if there was something unusual. Maybe something like "All footnotes are placed immediately after the paragraph of mention." or the opposite "All footnotes are placed at the end of the chapter."?

First summary should we have the statement "All Math is represented with MathML" since that would be covered by the MathML tag? If we keep it, it needs a full-stop at the end.

**Comment by GeorgeKerscher** [comment]
I made all the changes noted in this issue. In the transformability, I removed one example of a table, but kept the one that included the best practice of an image of a table with the real table in a details element below the image.
I added information about TTS markup from the pronunciation task force. I also made sure all items in the features table had an example and information.
