### ISSUE TITLE
[Grouping Accessibility Metadata] accessibilityFeature = bookmarks?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#149]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

Working on a system for grouping accessibility metadata into distinct categories the editors had this question that we repost in this issue so that it can be discussed by the community.

The question is about metadata `accessibilityFeature = bookmarks`: is the bookmarks feature related to the publication or the reading device? Is this related to PDFs?

**Comment by clapierre** [comment]
Sounds like this was related to PDF's, and I say for one let's move this out as this is specific to the Reading Device.  Now should we have a category for related metadata for "Reading Systems"?

**Comment by madeleinerothberg** [comment]
This feature was included in Schema.org for describing reading systems, not books. In the crosswalk this is noted as:

N/A (Reading system feature)

I think that means it should not appear in the guide to presenting metadata about books.

**Comment by MiiaKirsi** [comment]
I agree about leaving this out (or have a separate category for reading systems). Otherwise it could be confusing, as it's generally instructed that (accessible) PDFs should have bookmarks in them to help with navigation. Bookmarks provided by the PDF creator and bookmarks user can set up within a reading system are also two different things.

**Comment by rickj** [comment]
Per http://kb.daisy.org/publishing/docs/metadata/schema.org/accessibilityFeature.html this is NOT the "bookmark this page in my reading system" but rather references navigation in PDF's

**Comment by madeleinerothberg** [comment]
Rick, thanks for sharing that document. That is a different definition than given on the W3C vocabulary page:

https://www.w3.org/2021/a11y-discov-vocab/latest/#bookmarks:
4.2.1.3 bookmarks (deprecated)
The work includes bookmarks to facilitate navigation to key points.

NOTE
The use of the bookmarks value is now deprecated due to its ambiguity. For PDF bookmarks, the [tableOfContents](https://www.w3.org/2021/a11y-discov-vocab/latest/#tableOfContents) value should be used instead. For bookmarks in ebooks, the [annotations](https://www.w3.org/2021/a11y-discov-vocab/latest/#annotations) value can be used.

We may need a new issue/task to get those two sources of information in sync.

**Comment by rickj** [comment]
It's hard to deprecate a term that is canonical in Adobe's ecosystem https://www.adobe.com/acrobat/hub/how-to/learn-to-add-bookmarks-to-a-pdf

**Comment by gregoriopellegrino** [comment]
As decided in the [February 9 call](https://github.com/w3c/publ-a11y/wiki/Meeting-minutes-of-Publishing-CG-Accessibility-Task-Force#minutes-of-publishing-cg-accessibility-tf-meeting-held-on-february-9-2023-at-1500-utc) I moved `accessibilityFeature = bookmarks` to a section called **Out of scope (relative to reading solutions)**.
