### ISSUE TITLE
[Grouping Accessibility Metadata] accessibilityFeature = taggedPDF?

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#151]
This issue is part of the wider work presented in the issue #144 _Proposal for Grouping Accessibility Metadata into Categories_.

Working on a system for grouping accessibility metadata into distinct categories the editors had this question that we repost in this issue so that it can be discussed by the community.

The question is about metadata `accessibilityFeature = taggedPDF`: in which category do we place the tagged PDF metadata?

**Comment by clapierre** [comment]
As this is primarily relevant to PDF's this really shouldn't be an issue for EPUBs unless the EPUB contains a PDF which has been tagged.  Even in that case unless the contained PDF within the EPUB contains the content of the EPUB it self I wouldn't include "taggedPDF" metadata as an accessibilityFeature.  Think of this from the user's point of view searching in a library.  They are looking for a specific book and they want it to be a "taggedPDF" They wouldn't expect to get some random EPUB that contains a PDF.

This information would be provided instead in the accessibilitySummary that "contained in this EPUB is a taggedPDF with results also found in the appendix A" or something like that.

I think we don't include this to be honest as I can't see this happening in practice.

**Comment by madeleinerothberg** [comment]
Agree with Charles that this is not relevant to EPUBs. If it is present for a PDF book, it is the most basic of accessibility metadata needed for that book. For that reason I suggest leaving it in General Information as shown in the current draft.

**Comment by avneeshsingh** [comment]
Would like to remind that this guide is not for only EPUB publications. We expect retailers to use it no matter they are offering EPUB, PDF, Kindle or any other format.

**Comment by avneeshsingh** [comment]
The issue was resolved in February 23, 2023 meeting. The minutes follow:

Gpellegrino: w3c/publ-a11y#151

AvneeshSingh: tagged pdf is not a norm or conformance, more a feature.

gpellegrino: maybe similar to structural navigation

tzviya: there are few metadata’s related to specifics formats, this is the case of tagged as well a large Print for example.

CharlesL3: large Print could be used for Fixed Layout or PDF

proposed: tagged PDF should be moved to generic metadata

gpellegrino: +1

Jonas: +1

Tzviya: +1

CharlesL3: +1

Paulgilius: +1

Gpellegrino: so we leave it where it is :)

resolved

**Comment by gregoriopellegrino** [comment]
I am closing this issue, since no changes are required.
