### ISSUE TITLE
How to refer to braille

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#193]
We now use the term refreshable braille and electronic braille. We now know that ONIX uses the term digital braille to refer to the same thing. Should we add digital braille to  our note? Should we use the same term throughout?

**Comment by gautierchomel** [comment]
At least in France: 
* digital braille refers to a braille pre formatted file (like .brf).
* literal translation of the wording used for braille displayed by an electronic device would be: "ephemeral braille". (it can be pre formatted braille or dynamically generated one). 

I feel that _Refreshable braille_ is the technic while _Electronic braille_ is the mode of consumption.

**Comment by chrisONIX** [comment]
In ONIX we have quite a few references to braille as ONIX has always been able to carry information about books in braille - since the first version as it carries information about physical books. There is a code to indicate a braille edition - which is format neutral and you can also express a titles uses .brf as a format and here we use electronic braille in the notes. We do not currently use the term Digital braille in code lists or documents - but if it becomes a standard way of distinguishing from physical braille titles we would look at using it.

**Comment by gautierchomel** [comment]
Final choice was to add a note to https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/?updated#supports-nonvisual-reading

> The term "electronic braille" and "refreshable braille" are used interchangeably, which denotes a device with pop-up pins to present the braille on a tactile screen.

**Comment by riekevullings** [comment]
How 'closed' is this item? At Dedicon, we associate ‘electronic braille’ with digital formats rather than hardware. Since terms like ‘electronic braille’ or ‘refreshable braille’ are not commonly used (yet) in the publishing industry, shouldn’t we take this opportunity to integrate ‘refreshable braille’ into the vocabulary of publishers when referring to the hardware devices? This way, we can still use ‘electronic braille’ to distinguish electronic braille files (e.g., .brf) from text that is compatible with refreshable braille devices.

**Comment by mattgarrish** [comment]
The current definitions and use in the document seem contradictory.

First off, "refreshable braille" is never used in the documents despite the definition saying that the terms are used interchangeably.

Second, the definitions tie the terms to a braille device, but there only two uses of the "electronic braille". Both are in section 4.2 where the first instance says "reading systems using text-to-speech or electronic braille functionality". But it's not clear what "electronic braille functionality" is. That sounds different from a dedicated braille reading device as described in the definition.

The second use is in the examples. The first one says "All content is available in generated read aloud speech and electronic braille." Here, again, "electronic braille" sounds like a file format unless you catch on that "generated" applies to both read aloud and braille (i.e., it's not "generated read aloud speech" and "electronic braille", but "generated read aloud speech" and "generated electronic braille").

To fix the first instance, it might be clearer if it said "reading systems with text-to-speech or refreshable braille capabilities."

The examples might take a bit more work, as the content is only "available" in those formats if your device supports them. It's more of a possibility. For example, I'd probably rewrite the first example as:

> All content can be generated as read aloud speech or refreshable braille.

If I'm correctly interpreting the intent of this section, the others could be revised similarly.

**Comment by gautierchomel** [comment]
For reference, it was agreed in France to use  "All content can be generated as synthesized voice or braille" as the digital context makes it evident that it depends on a device (and neither refreshable nor electronic was understood). We considered using "ephemerous braille", but that was not universally understood either. 

Some braille users even mentioned that keeping only "generated as synthesised voice" was sufficient to let them understand they can read it in braille.

**Comment by riekevullings** [comment]
Thanks for your responses. Both suggestions make sense. Using 'can be generated' instead of 'is available in generated' avoids the impression that the content is already in speech or braille format. When leaving out referrals to hardware or software (read aloud speech, refreshable braille) it will be more future-proof. 
I guess 'All content can be generated as synthesized voice or braille' is simple and clear.

**Comment by GeorgeKerscher** [comment]
@mattgarrish Darn, thought I resolved the problems. Where do you want changes? Can you make a suggestion and do a PR?

**Comment by mattgarrish** [comment]
There are two problems with the definition in the terminology. One is that terms have to be used in the document in order to be formally defined. The term electronic braille is not used in the document so it can't be in a `dt` tag. The definition is also still slanted to defining a refreshable braille device, but the use of refreshable braille is for the generated content.

I also still find the claim that generated tts and generated braille are available misleading. As I've mentioned before, they can be generated if your device is capable of doing that. It's not that they're provided.

I can try creating a pull request, assuming that we're not trying to define a refreshable braille device. But do we want to call it refreshable braille or dynamic braille?

**Comment by GeorgeKerscher** [comment]
I am OK with dynamic  braille. I guess the point I want to make sure we make is that text content can be read by a person who has one of these devices. I think that is a helpful clarification for the public who does not come in contact with  people who have these devices.
