### ISSUE TITLE
Consistency about the display of metadata

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#246]
We need to be consistent in what we say about the display of the metadata. In the hazards section there is an an inconsistancy. Also we should review the text below:
This key information can be hidden if metadata is missing.
Indicates the presence of formulas (including math, chemistry, etc.), graphs, charts, and diagrams within the title and whether these are in an accessible format or available in an alternative form (e.g., whether formulas are navigable with assistive technologies, or whether extended descriptions are available for complex images).
This group should be displayed only if the metadata indicates the presence of formulas or charts and graphs within the title, otherwise it can be hidden.

So what should it be?

**Comment by GeorgeKerscher** [comment]
Below is what we have in the hazard section. We also need to be careful in the harzard section because one value is "unknown" and that is different from not knowing about the accessibility because of missing metadata.
It says:
This key information can be hidden if metadata is missing.

Identifies any potential hazards (e.g., flashing elements, background sounds, and motion simulation)
					that could afflict physiologically sensitive users.

Unlike other accessibility properties, the presence of hazards can be expressed either positively or
					negatively. This is because users search for content that is safe for them as well as want to know
					when content is potentially dangerous to them.

This group should always be displayed. Indicate that no metadata is provided if that is the case.

**Comment by gregoriopellegrino** [comment]
If I remember correctly, after a long discussion, we had decided to choose to indicate that the group can be hidden. Each implementer, depending also on the context in which his software will be used (e.g. trade publishing versus educational publishing), will be able to choose whether or not to show the group, even in the absence of metadata.

**Comment by madeleinerothberg** [comment]
The outcome of the most recent meeting was that we agreed to remove the sentence from the last paragraph that reads:
This group should always be displayed.

Still to decide is if we are keeping the following sentence that reads:
Indicate that no metadata is provided if that is the case.

As Gregorio noted, implementers can decide whether to show or hide this section if there is no metadata, so it isn't inappropriate to say "indicate no metadata" but it isn't really necessary either since the implementer will have made that decision independently. If we aren't including this line for any other optional metadata group, we should probably remove the whole paragraph as it was part of the previous decision, now overridden.

We may want a new paragraph that teases out "unknown" vs "no metadata". Here's a draft for comments:
The hazards property vocabulary includes a value of unknown, which means the author of the metadata explicitly acknowledges that the resource has not been checked for hazards. This is different than providing no metadata for this property which does not carry any meaning.

Editors, please make suggestions to improve or correct that draft. Do we need to account (in the Principles document) for the fact that schema.org has this explicit unknown value, while ONIX is actually going to be relying on a more general "accessibility unknown" value? Maybe that means this new paragraph does not belong in Principles but instead needs two different versions in the techniques documents.

**Comment by GeorgeKerscher** [comment]
Hi,
 
I made the change based on the suggestion from Madeleine.
 
I changed author to content creator because I don’t think authors are creating the metadata in most cases.
 
 
It is in PR 250:
https://github.com/w3c/publ-a11y/pull/250
 
Best
George

**Comment by GeorgeKerscher** [comment]
Closing because all the items have been addressed. If something is still missing, please file a new issue.
