### ISSUE TITLE
Align Hazards example

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#256]
The principles examples for Hazards are actually not aligned.

[EXAMPLE 14](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-descriptive-explanations-4): Descriptive explanations
 - The publication contains rapidly changing lights or visual stimuli, as well as simulated movements, which can cause discomfort, distraction, photosensitive seizures, or motion sickness.
 - No information about possible hazards.

[EXAMPLE 15](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-compact-explanations-3): Compact explanations
 - Flashing and motion simulation hazards.
 - No hazards.

**Comment by gautierchomel** [comment]
Proposal: 

[EXAMPLE 14](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-descriptive-explanations-4): Descriptive explanations
- The publication contains rapidly changing lights or visual stimuli, as well as simulated movements, which can cause discomfort, distraction, photosensitive seizures, or motion sickness.
- The publication contains no flashing, sounds or motion simulation hazards.
- The publication may contain possible flashing, sounds or motion simulation hazards.

[EXAMPLE 15](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-compact-explanations-3): Compact explanations
- Flashing, sounds or motion simulation hazards.
- No flashing, sounds or motion simulation hazards.
- Flashing and motion simulation hazards are unknown.

**Comment by madeleinerothberg** [comment]
This is a tricky section. Thank you, Gautier, for drafting this proposal.

Should we add statements for each hazard separately, since they may be known? The current examples only report "something might be a hazard" but not which kind of hazard.

The 2nd and 3rd bullets mention sound hazards, which are not mentioned in bullet 1 and which are not well defined, so perhaps we should omit them.

The descriptive version of bullet 3 is more frightening to me than the compact version -- "may contain" is not equivalent to "unknown" in my opinion. Is this a style that has been agreed to previously by the editors? If so, I will not object if others are fine with it. One possible rewording for the descriptive version is:

> Information about presence or absence of flashing, sounds or motion simulation hazards in the publication is not available.

The first bullet of Example 14 needs "or" instead of "as well as". As drafted it suggests that both types of hazards are present. That would create nested "or" statements, though. Is "visual stimuli" necessary in addition to rapidly changing lights? (In looking at the [vocab definitions](https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20230718/#accessibilityHazard-vocabulary), only flashing is mentioned.) If that can be skipped it would be possible to simplify the sentence, such as:

> The publication contains a hazard, such as flashing lights or simulated movements, which can cause discomfort, distraction, photosensitive seizures, or motion sickness.

or to keep visual stimuli, if we wish to describe the hazard in more detail than the vocabulary definition, perhaps separate it from flashing lights:

> The publication contains a hazard, such as flashing lights, rapidly changing visual stimuli, or simulated movements, which can cause discomfort, distraction, photosensitive seizures, or motion sickness.

**Comment by gautierchomel** [comment]
At meeting on April 25, it was decided:

* to check the pertinence and possibility of adding a check for presence of multimedia (but hazards can also come from animated Gifs or even CSS)
* add a note on Hazard / example
