### ISSUE TITLE
Need to harmonize Principles and Techniques on Non-Visual Reading

### ISSUE THREAD

**Issue by GeorgeKerscher** [w3c/publ-a11y#260]
The Principles has a different order than the techniques. Also, the principles has the value of unknown, which is not present in the techniques.

In particular the Techniques has the second and third item reversed from what is shown in the Principles.

**Comment by GeorgeKerscher** [comment]
The non-visual section in principles and in techniques should be the same order and content. The Principles has the value unknown and this is not in the techniques. Also the order of the three values are different.

**Comment by clapierre** [comment]
I am wondering if we need to adjust the Principals document instead because based on the logic of what we have available in both ONIX and EPUB there are only 3 possible combinations and their order to figure out programmatically are:

Readable in read aloud and braille.
Not fully readable in read aloud and braille
May not be fully readable in read aloud and braille

We don't really have the Unknown case unless you want to change the "may not be fully readable" option

**Comment by madeleinerothberg** [comment]
At meeting on April 25, it was decided:

- The order in Principles and Techniques documents may not be able to be aligned because the algorithm might be different for various metadata systems which would put the statements in different orders.
- "unknown" is needed for the three mandatory display topics, but not needed in the Principles document for other topics. It may be needed in the Techniques documents as the end-state of the algorithm.

**Comment by clapierre** [comment]
only add "unknown" in principals document for required top 3, and remove if found else ware in examples.
