### ISSUE TITLE
Clarifying the term "pagelist" for endusers

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#265]
While working on the techniques for ONIX accessibility metadata, I realized that the term "pagelist" we used in the examples might not be clear enough for end-users. We should consider providing a better explanation of this concept to ensure it's understandable to everyone.

Suggestions or alternative approaches to clarify this term are welcome.

**Comment by mattgarrish** [comment]
Something like "go to print page" functionality is available is probably more how end users will understand it.

The only concern is if publishers add the feature for books without a print equivalent. If the markers and page list are for virtual pages, then they aren't an accessibility feature. They're just a general usability feature. But maybe we can weed this case out by looking for a pageSource property of "none".

We should probably update the techniques document now to use the pageSource property, if so, as it still has the old source-of property.

**Comment by gautierchomel** [comment]
French vocabulary study ended with short sentence _Reference to printed book pagination_ and long sentences _The book can be used in addition to its printed version, with the reference pagination preserved._

**Comment by gautierchomel** [comment]
> Something like "go to print page" functionality is available is probably more how end users will understand it.

This is how reading system indicates the action that can be performed.

**Comment by jonaslil** [comment]
The compact explanation for navigation, now used in the Techniques, is "Navigation by table of contents, index, landmarks, and page list." I think "Navigation by ... print page numbers" or just "Navigation by ... page numbers" would be easier to understand. Or can we speak about "static page numbers" instead of "print page numbers", to allow for cases where there is no print equivalent?

In the ONIX case, speaking of *print* pages seems safe since the description of code 196:19 is "Print-equivalent page numbering". In Schema, this is less clear, as @mattgarrish noted.

As for the Schema techniques, I noted that the algorithm now only looks for the property `pageBreakMarkers`. But the `pageList` property is even more important. Many fixed layout books have page lists without page break markers. And page break markers alone will not enable page navigation.

The long explanation in the principles is "A page list enables users to coordinate their reading with a statically paginated version." I think it is fine to use the term page list if it followed by an explanation what the page list does. But the explanation is a bit abstract. I'll make an attempt at it: "A page list helps readers go to locations matching numbered pages in a print book or other statically paginated version."

**Comment by gautierchomel** [comment]
+1 to @jonaslil proposal:

> Static page numbers

> A page list helps readers go to locations matching numbered pages in a print book or other statically paginated version.

**Comment by mattgarrish** [comment]
> or from virtual page breaks and numbers

How is this an accessibility feature, though? It doesn't help anyone who doesn't have the exact same version of the ebook.

**Comment by avneeshsingh** [comment]
The issue was discussed in May 23, 2024 meeting

gpellegrino: PageList is the technical element in EPUB to the print page number. but PageList might not be understandable by end users. the effect of the page list "goto print page" as suggested by Matt, Reference to print pages by Gautier, and others as suggested in the issue.

George: page list enables goto page. but is also a link to that spot. it is content.
… it is exposed by the reading system. so goto print page number.

James: I would say goto page number because it may be virtual.
… A page list enables users to coordinate their reading with a statically paginated version."
… we do have pagebreakMarkers as an accessibility feature already

George: I think "Go To Page" is the key point here.

gpellegrino: saying only page navigation is not enough. You have pages and you go from one to the other. the actual issue here is synchronization is a substitute of the print version. we need to provide this information.

JonasLillqvist: string used in the techniques Navigation by ... feature for this is page list. my suggestion was to use maybe "static page numbers" or page numbers. so we get the navigation and page numbers and should be understandable.

AvneeshSingh: issue with pages two kind of pages, the reading system will show "screens" as pages only page navigation or goto page is ambiguous are we referring to page makers or screens.

George: we don't have navigation by screens, only by page list virtual or print book synchronized. that is what the content provides.
… Term I got Enables navigation by page numbers.

AvneeshSingh: any downside?

Charles: works for me.

AvneeshSingh: provide this term in the issue tracker. we can wait for comments. people like "Page Numbers" so this looks good.

**Comment by jonaslil** [comment]
Edit to my proposal for long explanation: omit the word 'statically'. It is implicit in the context. So the proposal is: "A page list helps readers go to locations matching numbered pages in a print book or other paginated version."

**Comment by gregoriopellegrino** [comment]
During the call for editors, we decided to lean toward "supports page navigation"
