### ISSUE TITLE
Clarifying the term "structured navigation" for endusers

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/publ-a11y#266]
While working on the techniques for ONIX accessibility metadata, I realized that the term "structured navigation" we used in the examples might not be clear enough for end-users. We should consider providing a better explanation of this concept to ensure it's understandable to everyone.

Suggestions or alternative approaches to clarify this term are welcome.

**Comment by mattgarrish** [comment]
Both the schema.org and onix definitions refer to this as being able to move by heading, so we should probably limit the description to that functionality. "Move to heading" or "Navigate by heading" maybe?

**Comment by avneeshsingh** [comment]
I think waht we want to convey is
Navigate by headings, pages, lists etc.

**Comment by gautierchomel** [comment]
The french study on vocabulary ended with short sentence _Logical navigation between the chapters_ and long sentence _The book's structure will be correctly interpreted by the reading devices._

**Comment by avneeshsingh** [comment]
The issue was discussed in May 23, 2024 meeting.

gpellegrino: two issues: structured Navigation that is not a great term for non-technical users. what would be a better term? to navigate through semantic elements.
… Matt suggested navigate by Headings, and Avneesh added, pages, lists, figures etc.
… Others have added additional suggestions in that issue.

George: Structured navigation is it clear "book Navigation?"

gautierchomel: structure as a sighted user does not mean anything. how assistive technology will interpret the book and allow for logical flow.
… like saying for a paper book that the pages are in the normal order. so we should try to define this concept.

gautierchomel: book will be correctly interpreted by a Reading system.

gpellegrino: correct reading order is a separate feature.

ccarr: Structural Navigation is that the same term in ONIX or are they using "structured" it’s the same term

JonasLillqvist: https://ns.editeur.org/onix/en/196/29

JonasLillqvist: Next Previous Structural navigation

ccarr: structural navigation was chosen as it is the most broad.

AvneeshSingh: so we should leave it as it is.

George: maybe change to "Structural" not "Structured"

gpellegrino: Examples should be given, by headings, pages, etc.

George: Book navigation by book constructs, table of contents, we don't know how often we get list of tables, figures.

gautierchomel: action is performable, by a screen reader.

AvneeshSingh: not only defined by screen readers, read-aloud

gautierchomel: user agent is the correct term but not understandable by average user.
… book element can be identified and accessed by AT or RS.

AvneeshSingh: We should be careful about AT / reading system  features and the capabilities enabled by the content, we can wordsmith in editors call.

George: Should I give a PR and we can refine it there?

AvneeshSingh: you can do a PR George that is fine. we can update issue tracker

**Comment by GeorgeKerscher** [comment]
Working on this in the principles.

The ID is: navigation-structural

The Descriptive string is:Contains book elements such as headings, tables, etc for structured navigation. 

The compact string is:  headings
