### ISSUE TITLE
Do we want to display Reason why the publication does not claim to meet the standards

### ISSUE THREAD

**Issue by gautierchomel** [w3c/publ-a11y#280]
At [Detailed conformance information](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#conf-aai) we suggest to display: 

> Reason why the publication does not claim to meet the standards. For some jurisdictions, it may be important to indicate why a publication is not compliant with the standards, such as if the company is too small and therefore not required to, or if the cost to produce the accessible version is too high. Showing this information may be important if required by local legislation, otherwise it can be omitted.

That's materialised by [EXAMPLE 7](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/draft/principles/#example-unknown-accessibility-conformance-statement-with-detailed-conformance-information): 

> Unknown accessibility conformance statement with detailed conformance Information
> Conformance to accepted standards for accessibility of this publication cannot be determined.
> 
> Detailed Conformance Information:
> 
> The creator of the publication is not required to publish in an accessible format because it is a micro-enterprise (e.g., enterprises employing fewer than 10 people and with annual turnover or balance sheet total not exceeding €2 million).

While this information is of use for control authorities, 

1. is this information valuable for the end user? and 
2. do publishers want their ebooks to be displayed with negative statements while in fact they will still probably have most of the accessibility features?

A side effect to consider is that an ebook can be made fully accessible because it's only text with a cover and logo as images, but to avoid burden and cost, the publisher indicates being exempted for micro-enterprise.  Some people may interpret this ebook as not accessible enough for them, while it is not the case.

**Comment by llemeurfr** [comment]
I would advocate that displaying this neutral information is a subtle way for the community to push small publishers to make some efforts to have positive information displayed.

**Comment by llemeurfr** [comment]
I'm not certain that small publishers will be happy to see their size exposed to the public this way. Let's listen to them on this point.

**Comment by LouisMarle** [comment]
Mention of exemptions for book accessibility should not appear.

1/ I agree with Laurent that some publishers don't want to reveal their size or sales or turnover (you don't ask for a lady's age, don't you?);
2/ the biggest publishers – which follow the european directive about accessibility and produce most of their e-books in a accessible way –  perhaps won't want to display exemptions for disproportionate burden and/or fundamental alteration of the work, so as not to appear like Scrooge, or even a smuggler (I heard this nice remark from someone at a meeting), especially if somebody claims that he has discovered a way to produce an accessible ebook from the same work (it can cause some confusion for the end user).
3/ It will give the opportunity to the small publishers to produce accessible ebooks and to mark them as such in the metadata fields. In this case, they won't have to indicate the value 75 of the list 196 (onix).

If the book is not indicated as accessible, the end user will be either ask for the reason via the site, which will be able to reply if it has the metadatas – or ask directly the publisher –, or (in the case of France) refer to ARCOM, which has the power to verify the veracity of the metadatas with the publisher. In both cases, the site will specify somewhere the process to be followed.

**Comment by gregoriopellegrino** [comment]
Since the guidelines are not strict requirements, but rather allow implementers some flexibility in how they choose to implement them, some implementers may decide not to display metadata regarding exceptions to the European Accessibility Act. 
 
Additionally, each publisher can manage which metadata they send to intermediaries (and other organizations of their choice), so they can decide whether to include information about an EAA exception or not on a granular basis - file by file, receiver by receiver. Their choice can be reflected in the metadata of file EPUB itself and in the ONIX record.
 
Therefore, we think it is important to maintain the example in the Principles document and related Techniques about EAA exceptions for those who wish to implement and display this metadata (where communicated by publishers). Those who do not wish to display exceptions can simply ignore that portion of the guidance.

**Comment by gautierchomel** [comment]
We believe this threatens publishers as they do not control what will happen, and implementers will not think to not display something in the guide. (i.e. having it here means it will be used).

On his side, the publisher might be obliged to provide that metadata for survey authority purposes. 

So we should explicitly recommend not to display it unless there's a legal obligation in the country. 

Having such information displayed should be publisher opt in, not opt out.

**Comment by chrisONIX** [comment]
So should the general advice be to display something like “this publication is not accessible and is not suitable for all ” without stating a reason - except when there is legal obligation to display an exact reason.
For ONIX - advice publishers to include code 09 -[Inaccessible, or known limited accessibility](https://ns.editeur.org/onix/en/196/09) - which can be sent with codes 75, 76, 77.

**Comment by gautierchomel** [comment]
> For ONIX - advice publishers to include code 09 -[Inaccessible, or known limited accessibility](https://ns.editeur.org/onix/en/196/09) - which can be sent with codes 75, 76, 77.

Those are great values for internal workflow, triage, and communication with regulation authorities. But
* As a publisher, I don't want my ebook to be sold with a negative statement 
* As a reader, I'm looking for an ebook that fits my needs (for example to adjust text aspect); if this information is not present, the ebook is not a good option for me. Any other statement is of no use and may trick me wrong.

**Comment by chrisONIX** [comment]
This information also needs to go to retailers and libraries so they can exclude it from their accessible titles or choose not to display or sell that product - depending on the jurisdiction. 
The Exceptions will let them know that they can sell or lend the product without so much legal risk. If there is no information then a default would be for retailers not to sell or to hide the title in jurisdictions with accessibility rules.

**Comment by gautierchomel** [comment]
Schema vocabulary makes it is clear that [none](https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20230718/#feature-none) or [unknown](https://www.w3.org/community/reports/a11y-discov-vocab/CG-FINAL-vocabulary-20230718/#feature-unknown) _must not be set with any other feature value_

Maybe we can make a check like IF no code from 196 is present, except 08 or 09, THEN we can optionally display something.

I would still prefer to clearly state that displaying negative statement is not recommended.

Displaying something from those metadata will certainly have the side effect of having them not used (because I don't want my books to be negatively anounced) and as a result will not help with triage and other uses.

**Comment by chrisONIX** [comment]
It makes sense that publishers do not want to see the three exceptions displayed on public sites but it is also important to make sure this information is included in the metadata. The best practice needs to emphasise that this is not recommended for public display - it is true it will mean absolutely nothing to most members of the public anyway -  they are mostly meant for bodies that will be in charge of enforcement. In fact we can say that these codes are in themselves inaccessible as they are based on legal jargon and are not for the average reader. 

They do not need to be displayed to the general public on public sites (unless there is a specific legal obligation in a jurisdiction or for a market type) but there  maybe other data receivers  in the supply chain who will need to make use of this information - for example if you are supplying to libraries, educational institutions or trying to create a catalogue of accessible titles and who may need to have this information accessible for their particular data partners, but this would normally be an informed audience. 

So maybe in the Conformance area we need a separate area that deals with metadata for non accessible titles and how to deal with this. An area for metadata for enforcement / conformance bodies only?
Should the principals document also give more information on why and when these exemptions are used? 

Also what do retailers display for titles that are not accessible to avoid customer service issues if someone purchases a title that is not readable on their device ? It will be the retailers that have to deal with the negative feedback from the public - not publishers - so the display guidelines should give some advice so that retailers  or libraries  can carry on selling or lending a title but customers know it will not be accessible for them? 
NB these are mostly titles that have no accessibility features listed in either ONIX or ePub if they are using the exemption codes. 
If there are any features listed in metadata then a retailer can display what is there and a customer can check to see if it is comptable. The importance is clarity for the potential reader. 

So we need a user friendly, easy language, non-negative suggestion of text for display that could be used when an ebook is not accessible or of very limited accessibility and  that publishers will understand is not a negative reflection on them but that consumers will also understand and will not have negative experiences when searching to purchase or borrow titles. 

The idea of the display is not to make publishers feel bad or look bad, but just to make sure that all consumers have the information they need to make informed purchases without having to go via a special route or making special requests. 

Did the French publishers have any suggestions for friendly phrases that a retailer could use ? 
Are we mostly talking about older titles, highly illustrated titles and fixed layout titles? We may be able to suggest friendly phrases around the limitations ?

This also links to the question - what happens if there is no metadata at all?  Do we use the same suggested friendly phrase?

**Comment by GeorgeKerscher** [comment]
First, the principles states:
NOTE
When the content creator does not provide any accessibility metadata for a publication, the three pieces of key information that should always be present can still be shown (with an indication that the information is missing): Visual adjustments, Supports nonvisual reading, and Conformance.

So the information that it is  missing would be displayed.

Then it says:
NOTE
In cases where the publication's compliance with accessibility standards is unknown, or it has known accessibility problems, it may be important for local legislation (e.g., the European Accessibility Act) to indicate why the publication is not accessible. This information could be contained in the Accessibility Summary, or as machine readable metadata, in which case the information should be given in the detailed accessibility information section.

We may want to emphasise that the publisher can clarify the accessibility of the publication or present what they think is appropriate in the accessibility summary. We could then state in example 7 that the details are not intended to be displayed to end users, or  We may want to remove the details entirely.

Thoughts?

**Comment by chrisONIX** [comment]
Proposal for this to be discussed: 

In the principals and techniques documents we need to include advice about displaying when a title may not be fully accessible, saying that it is good practice to give the maximum information about a title, including known limitations, as the principle is communicating information that will be useful for anyone who is receiving the metadata and anyone looking for titles. We need to approach this from the point of view of the whole international book supply chain. 

We should make it very clear that this is NOT mandatory to include the information - especially about exemptions - in the metadata  and that a publisher can choose not to include these values in their ONIX file and a website can also choose not to display this information. (Subject to a legal disclaimer). 

If a site does want to display the information, we should advise them to choose a user friendly text that is a reminder before purchase (or borrowing) to check if this title is suitable for you, rather than a statement that this title is inaccessible.
Retail sites do need to know if a title may not be fully accessible, because while they are not legally responsible for the accessibility of the ebooks - they are responsible for the accessibility of their e-commerce sites and providing clear and accessible information about **all** products and services they propose to consumers.

The advice about  display should be if any of these values are present in the metadata  - (the three EAA exemptions or the code saying inaccessible or of limited accessibility ) that a website can display a single friendly message - that is a message  that is not specific about the reason or reasons the title is of limited accessibility  - saying something like this 

 "_This title may not yet be fully accessible to all devices or readers and you should check the list of accessibility features to see if this title is suitable for your way of reading_”

This is just a suggestion of a text and somebody may have a better idea of a friendly text. This text gives a friendly warning, without being negative about the publisher or revealing anything about the exemptions. 

We can not ignore the need to give advice on the sharing and display of the metadata - but we do not want publishers to feel uncomfortable about including and sharing this information.

**Comment by chrisONIX** [comment]
So if we agree above then: 
Optional display - in the ONIX techniques document if these values from code list 196 are present - codes 75, 76, 77 or code 08 or 09 then display the following text:

"This title may not yet be fully accessible to all devices or readers and you should check the list of accessibility features to see if this title is suitable for your way of reading”

**Comment by gautierchomel** [comment]
There's confusion between "accessibility conformance unknown" and "accessibility unknown". 

When conformance is not present, it is of interest to have it informed, but the actual display suggestion is not saying that there is "no or unknown conformance", it says there is "no or unknown accessibility".

**Comment by gregoriopellegrino** [comment]
Right. I think it is because Chris proposal is referring to specific ONIX metadata where publishers - if they want - can declare it:

- code 08: [Unknown accessibility](https://ns.editeur.org/onix/en/196/08)
- code 09: [Inaccessible, or known limited accessibility](https://ns.editeur.org/onix/en/196/09)

From my point of view, if these codes are not present and there is no conformance information, then it is "no or unknown conformance".

**Comment by gautierchomel** [comment]
Another way is to ignore those codes and base "unknown conformance with accessibility standard" on the simple absence of any conformity code. That would reinforce their meaning for workflow, control, and filtering by making sure that they are not used to trigger or avoid a display.

That would also simplify and clarify the parallel techniques between ONIX and EPUB metadata and ensure the displayed information is obtained from metadata with similar meaning.

**Comment by clapierre** [comment]
I agree here with @gautierchomel lets not conflate two sets of metadata and keep the conformance based on the conformance metadata itself being present / missing.

**Comment by chrisONIX** [comment]
I agree with @gregoriopellegrino the proposal was not about the conformance values in ONIX but about the display of information about limited accessibility or inaccessible. This maybe should have been under a different issue 
I did not want to confuse Conformance and other metadata. 
Conformance is meaningless to non-specialists

**Comment by gautierchomel** [comment]
I am closing this as a consensus has been found on displaying one generic sentence for any exemption or exception. The advantage is that it can apply to any legislation other than EAA. 

Discussion follows at #350
