### ISSUE TITLE
Changing of the Label to "Full Audio"

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#36]
As discussed in the PCG-A11Y meeting at [https://www.w3.org/2021/02/05-pcg-a11y-minutes.html](https://www.w3.org/2021/02/05-pcg-a11y-minutes.html)

We decided to change how accessModeSufficient=audio is exposed to end users.
"Audio Book" has a preconceived public opinion of what that is so instead we will change our label to "Full Audio" instead

This impacts all 3 documents

- [https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/#audiobook](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/#audiobook)
- [https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/epub-metadata.html#audiobook](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/epub-metadata.html#audiobook)
- [https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/onix.html#audiobook](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/onix.html#audiobook)

In addition to just changing the label we also need to update the definition of what "Full Audio" means as well as the "Rational"

Currently:

4.2 Audiobook

Values: Yes / (if No - Omit this section)

Definition

An indication that this publication is an audiobook which is designed to be used by listening. This designation can be applied if text will also appear on a display as long as it is not required to use the publication.

Rationale

Audiobooks are considered optimized publications. They may not meet all accessibility requirements if they lack visible text, but they provide access to the publication for specific users who require audio, including users with dyslexia or visual impairments. Providing a way for users to search a collection for audiobooks will support these users, and including this information in the metadata displayed will also alert users for whom audio is inaccessible. This piece of metadata should be included only if the value is "Yes". Since most digital publications available are not audiobooks, it is only important to include this metadata in the user interface for those that are.

**Comment by madeleinerothberg** [comment]
Proposed new language (see original in @clapierre's post above.) Is this too much detail?

4.2 Full Audio

Values: Yes / (if No - Omit this section)

Definition

An indication that this publication can be used by listening. This designation can be applied if text will also appear on a display as long as the text is not required to use the publication.

Rationale

Some users, including users with dyslexia or visual impairments, seek books they can use entirely by listening. Full audio metadata is important to the discovery process for these users. Book providers, vendors, and libraries may already be designating "audiobooks" as a separately searchable set based on the popular definition of an audiobook as an audio-only experience. Publications that include full text and full audio may not currently be grouped with audiobooks, so exposing this metadata adds additional publications to the list of titles audio users might be interested in.

Audiobooks presented without text are considered optimized publications. They do not meet all accessibility requirements, and therefore will not be discovered when filtering for "accessible" books, but they provide access to the publication for specific users who require audio. Providing a way for users to search a collection for all books with full audio will support these users, and including this information in the metadata displayed will also alert users for whom audio is inaccessible. This piece of metadata should be included only if the value is "Yes". Since most digital publications available do not include audio, it is only important to include this metadata in the user interface for those that do.

**Comment by GeorgeKerscher** [comment]
Should we add something that there is full text with the full audio? So a title that is fully synchronized text and audio would get values for AccessModeSufficent as textual, audio, full audio.

**Comment by madeleinerothberg** [comment]
In this doc, we aren't getting into the specifics of the EPUB/Schema metadata. We could add a sentence noting that a book with full text and full audio would be noted both as an audio book and as screen-reader friendly.

**Comment by HadrienGardeur** [comment]
"Full audio" makes a lot more sense than "Audiobook", but could we also follow the same approach for text ("Full text" instead of "Screen Reader Friendly") for the sake of consistency?
