### ISSUE TITLE
accessibilityHazard:none incorrect UI

### ISSUE THREAD

**Issue by clapierre** [w3c/publ-a11y#43]
In Section 2.8.5 when the accessibilityHazard metadata is = "none" the UI should not say "None provided" because there was metadata provided.

It should say 
Omit this Section
or
Hazards: none
or
Hazards: No Flashing, No Sound, No Motion Simulation.

**Comment by gregoriopellegrino** [comment]
I would prefer `Hazards: none`

**Comment by GeorgeKerscher** [comment]
I am OK with none as well.

**Comment by avneeshsingh** [comment]
I think we can make this change in user experience guide.

**Comment by clapierre** [comment]
The only issue here is that the reason we added "Omit this section" as an option was for the following.

Nothing presented to the user because there are no hazards; since 99.9% of EPUBs won’t have any hazards, there is no need to report Hazards: None for every EPUB.

Do we still feel this way or we really want to see Hazards: none for every EPUB?

**Comment by avneeshsingh** [comment]
It looks that the principles document is in-sync with our above discussions it says:
Unlike other accessibility properties, the presence of hazards can be expressed either positively or negatively. This is because users are more often looking for content that is safe for them. This section should always be displayed; indicate that no metadata was provided if that is the case.
https://w3c.github.io/publ-a11y/UX-Guide-Metadata/principles/#hazards

But in techniques we suggest to omit hazards if it is none. I am leaning towards following principles document.

**Comment by avneeshsingh** [comment]
To summarize:

If there is a hazard like flashing hazard then UI should convey it:
Hazard: Flashing

If metadata reports No Flashing, No Sound, No Motion Simulation then UI can convey:
Hazards: No Flashing, No Sound, No Motion Simulation.
or
Hazards: none

If metadata is not provided or hazards is explicitly mentioned as "unknown in metadata". Then UI should convey:
Hazards: unknown
Another way can be to convey "unknown" if hazard metadata has value "unknown" and convey "none provided" if hazard metadata is missing. But I think that this detail will not make much difference for the users. So, in favor of simplicity, we can stick to displaying "unknown" in both the cases.
